#auth_token: eKJX8iasCZSMNHTes3rQ
#repositories:
#  - title: 'travelpayouts'
#    branch: master
#    repository: KosyanMedia/travelpayouts
#type: pro
org:
  auth_token: eKJX8iasCZSMNHTes3rQ
  repositories:
  - title: 'travelpayouts'
    branch: master
    repository: KosyanMedia/travelpayouts
  type: org
pro:
  auth_token: eKJX8iasCZSMNHTes3rQ
  repositories:
  - title: 'travelpayouts'
    branch: master
    repository: KosyanMedia/travelpayouts
  type: pro
